return {
	-- "Vigemus/iron.nvim",
	-- config = function()
	-- 	local iron = require("iron.core")
	-- 	local view = require("iron.view")
	-- 	local common = require("iron.fts.common")
	--
	-- 	iron.setup {
	-- 		config = {
	-- 			-- Whether a repl should be discarded or not
	-- 			scratch_repl = true,
	-- 			repl_definition = {
	-- 				sh = {
	-- 					command = { "zsh" }
	-- 				},
	-- 				python = {
	-- 					command = { "ipython", "--no-autoindent" },
	-- 					block_dividers = { "# %%", "#%%" },
	-- 				}
	-- 			},
	-- 			repl_open_cmd = "vertical botright 70 split"
	-- 		},
	-- 		-- Iron doesn't set keymaps by default anymore.
	-- 		-- You can set them here or manually add keymaps to the functions in iron.core
	-- 		keymaps = {
	-- 			toggle_repl = "<space>rr", -- toggles the repl open and closed.
	-- 			restart_repl = "<space>rR", -- calls `IronRestart` to restart the repl
	-- 			send_motion = "<space>sc",
	-- 			visual_send = "<space>sc",
	-- 			send_file = "<space>sf",
	-- 			send_line = "<space>sl",
	-- 			send_paragraph = "<space>sp",
	-- 			send_until_cursor = "<space>su",
	-- 			send_mark = "<space>sm",
	-- 			send_code_block = "<space>sb",
	-- 			send_code_block_and_move = "<space>sn",
	-- 			cr = "<space>s<cr>",
	-- 			interrupt = "<space>s<space>",
	-- 			exit = "<space>sq",
	-- 			clear = "<space>cl",
	-- 		},
	--
	-- 		-- If the highlight is on, you can change how it looks
	-- 		-- For the available options, check nvim_set_hl
	-- 		highlight = {
	-- 			italic = true
	-- 		},
	-- 		ignore_blank_lines = true, -- ignore blank lines when sending visual select lines
	-- 	}
	-- end
}
